Unify to PostgreSQL C conventions, add comments
pg-redis-fdw/redis_fdw pull request #40
Opened 2024-12-06 11:40 UTC by mkgrgis

In this PR

- improve readability of some files
- fix code style nearer to PostgreSQL C conventions
- remove trailing spaces
- fix some spell problems
- reorder of connection/table options according to comments
- add/restore some comments by PostgreSQL FDW example
- encapsulate default void values set for `table_options` structure to `redisGetOptions` (this was 3x doubled code)
- implement error message about unknown table type by TODO comment

2025-01-21 09:41 UTC, dpage requested changes

2025-01-21 09:41 UTC, dpage commented on README.md
> +- A Redis database accesible from PostgreSQL server.
accessible

2025-01-21 09:41 UTC, dpage commented on README.md
>  No deb or rpm packages are avalillable.
Can you fix this whilst passing?

2025-01-21 09:41 UTC, dpage commented on README.md
> +to [Redis](http://redis.io/) key/value database. This FDW works with PostgreSQL 10+
"key/value databases" (plural).

2025-01-21 09:41 UTC, dpage commented on README.md
> +`redis_fdw` **don't support** [IMPORT FOREIGN SCHEMA](https://www.postgresql.org/docs/current/sql-importforeignschema.html) and accepts no custom options for this command.
"doesn't support"

2025-01-21 09:41 UTC, dpage commented on README.md
> +If there will no proper name qouting in PostgreSQL, access from PostgreSQL foreign tables
s/qouting/quoting

2025-01-21 09:41 UTC, dpage commented on README.md
>  All strings from Redis are interpreted acording to the PostgreSQL database's server encoding.
LEt's update this to:

All strings from Redis are interpreted acording to the PostgreSQL database's server encoding.
Redis supports UTF-8 only data. It's not a problem if the PostgreSQL server encoding is UTF-8.
Behaviour with non-UTF8 PostgreSQL servers is undefined and untested.
It is not recommended to use `redis_fdw` with non UTF-8 PostgreSQL databases.

2025-01-28 10:48 UTC, mkgrgis commented on README.md
> +- A Redis database accesible from PostgreSQL server.
Please verify https://github.com/pg-redis-fdw/redis_fdw/pull/40/commits/e258ae6ff624b0c6e04ddffd219395a18626e5dc if all is ok now.

2025-01-28 10:49 UTC, mkgrgis commented on README.md
>  No deb or rpm packages are avalillable.
No, this is not simple procedure. I have requested any instructions from pgsql-pkg-debian@lists.postgresql.org , but there is still no answer.

2025-01-28 10:49 UTC, mkgrgis commented on README.md
> +to [Redis](http://redis.io/) key/value database. This FDW works with PostgreSQL 10+
Done in https://github.com/pg-redis-fdw/redis_fdw/pull/40/commits/e258ae6ff624b0c6e04ddffd219395a18626e5dc , please recheck.

2025-01-28 10:50 UTC, mkgrgis commented on README.md
> +If there will no proper name qouting in PostgreSQL, access from PostgreSQL foreign tables
Fixed in https://github.com/pg-redis-fdw/redis_fdw/pull/40/commits/e258ae6ff624b0c6e04ddffd219395a18626e5dc , please verify.

2025-01-28 10:50 UTC, mkgrgis commented on README.md
>  All strings from Redis are interpreted acording to the PostgreSQL database's server encoding.
Updated in https://github.com/pg-redis-fdw/redis_fdw/pull/40/commits/e258ae6ff624b0c6e04ddffd219395a18626e5dc, please recheck.

2025-02-03 17:27 UTC, mkgrgis commented on README.md
>  No deb or rpm packages are avalillable.
@dpage , I'll try to add debian metadata for PGDG (PostgreSQL development group) in some days.

2025-02-04 14:44 UTC, dpage commented on README.md
>  No deb or rpm packages are avalillable.
I meant the typo, not the lack of packages :-)

2025-02-04 16:37 UTC, mkgrgis commented on README.md
>  No deb or rpm packages are avalillable.
> I meant the typo, not the lack of packages :-)

Fixed, no problems. PGDG can try to make `redis-fdw` packages as group of experimental binary packages in 20-30 days and I am discussing about harder SQLite FDW now with package engineer. Look like there will be separate PR for `debian` directory with metadata.

2025-02-05 04:34 UTC, mkgrgis commented
@dpage , could you please describe a standard testing process for the FDW? copying to `contrib` of compiled PostgreSQL source code tree and `make && make install && make installcheck` is not enough.

2025-02-05 09:12 UTC, merged

2025-02-05 21:49 UTC, adunstan commented
> @dpage , could you please describe a standard testing process for the FDW? Copying to `contrib` of compiled PostgreSQL source code tree and `make && make install && make installcheck` is not enough.

In what sense is it not enoug?. This is essentially the process followed by the buildfarm module. See `https://github.com/PGBuildFarm/client-code/blob/main/PGBuild/Modules/RedisFDW.pm` Of course, you need a running postgres server to run it against. That's how `installcheck` works. There is no requirement to copy anything to `contrib`.

2025-02-06 04:49 UTC, mkgrgis commented
Thanks for fixing and explanation @adunstan ! https://github.com/PGBuildFarm/client-code/blob/main/PGBuild/Modules/RedisFDW.pm was helpful.